export const initParams = [
  {
    name: "Default",
    value: {
      welcome: ["A story", "of", "halloween"],
      firstText: [
        `Halloween`,
        `or`,
        `Hallowe'en`,
        `( a`,
        `contraction`,
        `of`,
        `"All`,
        `Hallows'`,
        `evening" )`,
      ],
      secondText: [
        `It`,
        `is`,
        `about`,
        `remembering`,
        `the`,
        `dead,`,
        `including`,
        `saints`,
        `(hallows),`,
        `martyrs,`,
        `and`,
        `all`,
        `the`,
        `departed`,
      ],
    },
  },
];
